version: '3.8'

services:
  ech-proxy:
    image: ghcr.io/dirige/ech-proxy-panel:latest
    container_name: ech-proxy
    restart: always
    ports:
      - "9090:9090"
      - "30000:30000"
    volumes:
      - /ikuai/docker/ECH/data:/data
    command: >
      -l 0.0.0.0:30000
      -f 你的服务地址:443
      -token 你的令牌
      -web :9090
      -routing global
